### ISSUE TITLE
Publish Feliz.Markdown

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#111]
I can't find Feliz.Markdown on NuGet. I'd like it for the MUI docs. (I'm open to other good solutions, though.)

**Comment by Shmew** [comment]
I just pull down the file from github via paket for my docs

**Comment by cmeeren** [comment]
Currently not using paket for Feliz.MaterialUI. In any case, it would be great to have it as a published NuGet with some docs on the Feliz homepage. :)

**Comment by Zaid-Ajaj** [comment]
@cmeeren I haven't published Feliz.Markdown because it does not fully support the `react-markdown` api and it is not fully documented, especially when it comes to plugins and renderers. I wanted to only publish those (high-quality) bindings that are well documented, tested etc. I am not sure `Feliz.Markdown` counts as one of those even though it is quite usable.

**Comment by cmeeren** [comment]
I see. Still, I see nothing wrong with publishing a 0.x which is by definition incomplete.

I mean, the whole Feliz ecosystem is still at 0.x 😂

I know I'd use it at least, though I won't force it on you if you'd rather not.

**Comment by Zaid-Ajaj** [comment]
Published here https://www.nuget.org/packages/Feliz.Markdown/ :smile:

**Comment by cmeeren** [comment]
Hooray! 🎉
