### ISSUE TITLE
inheritFromParent -> inherit'

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#12]
Since `inherit` is a reserved keyword, what about simply adding an apostrophe (`inherit'`) instead of coming up with another name (`inheritFromParent`)?

**Comment by Zaid-Ajaj** [comment]
Same as my comment [here](https://github.com/Zaid-Ajaj/Feliz/issues/13#issuecomment-520400763) I am trying to avoid apostrophe in naming. `inheritFromParent` derives the naming from what it does and considering how uncommon this construct will be used (ofc. just a guess, I don't have numbers) it is good enough

**Comment by cmeeren** [comment]
Replying to the above as well as your comment in that issue: I'm not an F# beginner, but when I was, I didn't see any problem with `'` (neither do I now). In fact, I thought it was a great way to avoid clashes with reserved keywords and used it wherever needed (and still do). That's me, though. :)

**Comment by cmeeren** [comment]
(For completeness: Another alternative is to use double backticks, ` ``inherit`` `, but I vastly prefer a single apostrophe to double backticks in this case.)

**Comment by cmeeren** [comment]
Just want to note that I consistently append `'` to reserved keywords in Feliz.MaterialUI. That way:

* Users intuitively understand that e.g. `color.default'` refers to the MUI `default` color
  * I expect users would be confused by alternative names like `color.standard` or `color.normal` and annoyed at more verbose alternatives like `color.defaultColor`, and all of these could also clash with new additions in MUI
* I avoid having to come up with custom names for a lot of props

IMHO it looks great in usage, too. :) I suggest doing the same in Feliz, but it's ultimately your call, of course. (And I'm open to hearing better ways of doing things in Feliz.MaterialUI too, of course.)

**Comment by Zaid-Ajaj** [comment]
I agree it makes sense in Material UI context but not really in this base library because of how uncommon it is used and it is here the only one (I think along with `type'` for which I used `inputType`)

I will leave this issue open for a while, maybe someone can enlighten our subjectiveness :)

**Comment by cmeeren** [comment]
Forgot to mention in #42 but I'd just like to be open about the fact that I added one such apostrophe name (`ariaAutocomplete.inline')`:

https://github.com/Zaid-Ajaj/Feliz/blob/0615e786faa34a411b461072c01aa6d3d919abce/src/Properties.fs#L871-L885

if you don't like it, feel free to rename it. :)

**Comment by Zaid-Ajaj** [comment]
Thanks for sharing, I didn't see it there but (just as you said) I find it hard to come up with my own versions of names: `inlinedSuggestions`, `inlined`, `inlineSuggestion` etc.

**Comment by cmeeren** [comment]
Also, feel free to close this issue if you feel the final decision has been made on `inheritFromParent` vs. `inherit'`.

**Comment by Zaid-Ajaj** [comment]
Last comments on `inheritFromParent` before I close the issue
 - Doesn't use prime and backticks to make it look not so foreign (no F#-ers) for newcomers, especially inside online editors (github) 
 - Reflects what it does in the name
 - Not used commenly so the long name will (hopefully) not discourage people from using the value too often when needed

As for `ariaAutocomplete.inline'` I will go for `ariaAutocomplete.inlineAfterCarret` because that is what the description says about the attribute.

Found a serious issue with this decision? Please open a new issue and let us discuss it :smile:

**Comment by cmeeren** [comment]
Shouldn't it be `inlineAfterCaret`? (Single `r`)

**Comment by Zaid-Ajaj** [comment]
Sorry I wrote incorrectly here but added the right one (with single `r`) in the props

**Comment by zanaptak** [comment]
Just pointing out that underscore is also an option to consider, either trailing or leading (e.g. `inherit_`, `_inline`). It's not as foreign as apostrophe since other languages and editing tools usually also allow underscores in identifiers.

I am not suggesting it for this issue. Decision to use word suffixes is perfectly fine. Just felt like an overlooked option to add to the discussion in case it helps any other onlookers.

**Comment by cmeeren** [comment]
Yep, though prefixing with underscore in F# usually means that it's an unused value (prefixing with underscore suppresses unused warnings).
