### ISSUE TITLE
pseudo-class (:hover, :active) support

### ISSUE THREAD

**Issue by zanaptak** [Zaid-Ajaj/Feliz#121]
A limitation of inline style properties on elements is that they don't support pseudo-classes (e.g. `:hover`, `:active`).

Libraries such as JSS or elm-css work around this by adding dynamically generated classes to the document, via local `<style>` tag or browser stylesheet API `insertRule()`.

[Here is a description of the technique used by elm-css.](https://github.com/rtfeldman/elm-css/blob/33361d3eca52d110f90639a69644066f6219234f/src/Css.elm#L206-L249)

Perhaps this capability could be considered as a feature suggestion for Feliz.

**Comment by MangelMaxime** [comment]
My advice for such case is to use a CSS stylesheet in your project. In general, you always have a CSS framework or a stylesheet included in your project because it gives you more control and helps to keep the code and DOM clean.

Injecting CSS also means Feliz has to generate and include some unique IDs to the elements, how to make sure it produces the same IDs for the same element between re-draws, or when the destroying the element and re-rendering again (after navigation for example).

For me having a library which manipulates my DOMs by default is a no go. In the era of bootstrap & co, we always ended up fighting it because of the unexpected side-effects.

Also, if Feliz starts to inject some CSS into the DOM, it will have support HMR for it, and it will be challenging to do it right.

From my point of view, Feliz is a layer on top of React. If you want this kind of features are added it should be done in separate library like it is for Elm and React eco-system.

**Comment by Zaid-Ajaj** [comment]
Hello @zanaptak, like @MangelMaxime said, this is a nice to have in the long run as a companion library working next to Feliz and binding to an existing library might be a better choice since we won't have to solve problems that people have already solved (especially with regard to HMR and dev experience).

> Injecting CSS also means Feliz has to generate and include some unique IDs to the elements, how to make sure it produces the same IDs for the same element between re-draws, or when the destroying the element and re-rendering again (after navigation for example).

You can memoize the generated ID and document that you define these classes once in a module as opposed to defining them inside the render itself (much like React.functionComponent)

**Comment by Zaid-Ajaj** [comment]
Looking at [Fela](https://github.com/robinweser/fela) and looks like a nice addition to the Feliz ecosystem, I will keep an eye on but currently I don't have time to start another project
