### ISSUE TITLE
Interpret more className properties as append

### ISSUE THREAD

**Issue by Dzoukr** [Zaid-Ajaj/Feliz#128]
If you create custom `IReactProperty` with setting class name like `isActive`, `isPrimary`, you can use it with Feliz like:

```fsharp
Html.div [
    isPrimary
    isActive
    prop.text "Hello Feliz"
]
```

the output of this will consider only the last set `className`. I think for better usage of custom helper functions (and future DSLs over Feliz) the default behavior should merge `className` together.

What do you think?

**Comment by Dzoukr** [comment]
Just FYI, I am already doing that for `Feliz.Bulma` to work properly, but some support out-of-the-Feliz-box would be great. 😄 

https://github.com/Dzoukr/Feliz.Bulma/blob/master/src/Feliz.Bulma/ElementBuilders.fs#L13-L17

**Comment by MangelMaxime** [comment]
> the output of this will consider only the last set className.

This is because it is the behaviour of react.

If Feliz was having this new feature I would prefer it to use a custom property for it and keep `className` the direct wrapper it is right now.

**Comment by Dzoukr** [comment]
> If Feliz was having this new feature I would prefer it to use a custom property for it and keep className the direct wrapper it is right now.

Totally agree - the it wouldn't even be a breaking change.

**Comment by Dzoukr** [comment]
Btw, I am totally ok to send a PR, if approved by @Zaid-Ajaj. Also need to think about correct property name (naming is hard :)).

**Comment by Zaid-Ajaj** [comment]
Hello Roman,

I have thought about this before but can be a bit problematic for Feliz to specifically extract `className` properties. Right now, Feliz makes an object literal directly from the input list of `IReactProperty` using `createObj` and passes it to the props of the React components. Having to aggregate the `className` property from each  list for each element means an additional runtime overhead due to the searching for `className` and other properties that can be avoided for most use-cases since this *append behavior* can already be defined as a list input for the `prop.className` function:
```fs
module Bulma = 
  let [<Literal>] button = "button"
  let [<Literal>] isPrimary = "is-primary" 

Html.button [
  prop.className [ Bulma.button; Bulma.isPrimary ]
  prop.text "Click me"
]
```
It might make sense for an extension library such as that of Feliz.Bulma (I think even Fulma does some pre-processing on the input list to search for `children`) but in the general case of Feliz, I would like to avoid that additional overhead if possible

Unfortunately right now I don't have numbers of the significance of runtime overhead caused by the extra processing but is ~O(n*m) operation because we are checking n input props for each m elements 

> If Feliz was having this new feature I would prefer it to use a custom property for it and keep className the direct wrapper it is right now.

> Totally agree - then it wouldn't even be a breaking change.

As mentioned above, this custom property is already available as an overload for `className` which takes a list of classes as input and concatenates them

**Comment by Dzoukr** [comment]
Thanks for the explanation, I'll try to workaround it somehow for now.
