### ISSUE TITLE
Is it easy to publish a React JS component from Feliz?

### ISSUE THREAD

**Issue by jchain** [Zaid-Ajaj/Feliz#142]
Can I write a React component in Feliz and publish it as a pure JS component easily for JS developers who have zero background of F#/Fable?

I compared `Feliz` and [`Fable-React`](https://github.com/fable-compiler/fable-reactl) and IMHO `Feliz` code is more intuitive (easier) than `Fable-React`. `Faliz` document is very helpful but it feels like we write component in a Feliz project and use it (exclusively) in a Feliz project. That limits the scope of audience. In [fable2-sample](https://github.com/fable-compiler/fable2-samples), there is a `reactComponent` repo. Although too simple the example is, it at least shows a way of how to do it. I'm confused if Feliz can do the same thing.

**Comment by MangelMaxime** [comment]
Because Fable generates JavaScript, in the same way you consume JavaScript library you can also consume F# code or libraries from JavaScript.

You can more info on this page: https://fable.io/docs/communicate/fable-from-js.html#Call-Fable-compiled-code-as-a-library.

As an example, Nacara is a library made using Fable but I can use it from JavaScript:

```fs
const prelude = require('nacara/dist/layouts/standard/Prelude');
const markdown = require('nacara/dist/js/utils').markdown;
```

**Comment by Shmew** [comment]
Looks like this has been answered, feel free to re-open the issue if you have any more problems/questions.
