### ISSUE TITLE
Support for Fable React native

### ISSUE THREAD

**Issue by mohandev** [Zaid-Ajaj/Feliz#146]
Hi, Wondering if you have plans to release this library for Fable React Native ?

**Comment by Zaid-Ajaj** [comment]
Hello there! Yes there are plans to implement a proper React Native API in Feliz style. However, it won't be in the near future since there is still much work to do around Feliz itself and its ecosystem. In case you would like to contribute, I would really appreciate it and will gladly review your PRs :smile:

**Comment by mohandev** [comment]
Got it. Thanks for the info :)
