### ISSUE TITLE
Potential Bug: Missing tags when using Preact

### ISSUE THREAD

**Issue by l3m** [Zaid-Ajaj/Feliz#190]
I've tried to convert an existing larger site of mine from Fable.React to Feliz. It uses Preact (atm v10.3.1), and this works flawlessly with Fable.React. 

Converting it to Feliz, I noticed missing tags. It seems that some children are not even in the dom, and some pages are just empty except for the root tag. 

I managed to reproduce the problem partially using the SAFE.Simplified example, in the preact-1 branch (https://github.com/l3m/SAFE.Simplified/tree/preact-1)

In the example, the counter tag is empty, too, when using preact, works when going to master and using react. In both SAFE.Simplified and my site I can make it work/break it by simply checking out the commit with react/preact, reinstalling deps and building.

**Comment by Zaid-Ajaj** [comment]
Hi @l3m, I don't we have done anything special to make Feliz work for Preact 🤔 according to the premise of preact/compat, it "should" work out of the box but looks like it doesn't.

I will investigate it soon

**Comment by l3m** [comment]
Ok, it seems that latest preact also breaks Fable.React. So this doesn't seem to be a Feliz problem. Closing the issue.

**Comment by l3m** [comment]
I closed and reopened because I thought preact also broke React.Fable, but turns out I just had a Feliz component high up in the dom tree and that broke it.

**Comment by BennieCopeland** [comment]
I poked around a little bit and did some testing. It works with a list of `ReactElements`, but as soon as you add an `if` or `match` expression in the middle of the list it breaks. Additionally, if I pull a working list out into its own `let` bound value, it stops working.

Works:
```fsharp
prop.children [
    Html.text "Blah"
]
```

Doesn't work:
```fsharp
prop.children [
    if true then Html.text "Blah"
]
```

Also doesn't work:
```fsharp
let children = [
    Html.text "Blah"
]
...

prop.children children
```

**Comment by BennieCopeland** [comment]
I think this [Preact issue](https://github.com/preactjs/preact-compat/issues/262) is related. I got all failing cases above to work by using arrays instead of seq or list.

**Comment by VitalyBrusentsev** [comment]
@Zaid-Ajaj is it possible to add another overload to `prop`? It could solve the preact issue without making breaking changes.

As stated by @BennieCopeland, the issue is that Preact does not support iterators for `children` (and that's what Fable generates when it encounters lists with dynamic contents). This is strange, as lists in F# are supposed to be eagerly computed (not sure why Fable thinks otherwise).
If lists were materialized into arrays, Preact would work just fine (and save us tons of traffic and load time! :) )

I managed to make my views work with eager seq materialization and this definition overshadowing the original `prop.children`
```
let childrenInternal elems = elems |> Array.ofSeq |> prop.children
module prop =
  let children = childrenInternal
```

If you added an overload of `prop.children` taking `ReactElement list` instead of `seq` (and materializing the list to Array, as above), this issue would be solved. The users of `seq` overload would need to use React, but the list version would be compatible with Preact.

I can create a PR if you are interested.

**Comment by Shmew** [comment]
I don't see a compelling reason for this not to just be a list rather than seq anyways. Shouldn't really break anything afaik.

**Comment by Zaid-Ajaj** [comment]
I just published v1.8 that converts the elements into arrays before being passed into `Children.toArray` from React. I think that fixes the problem for now. @VitalyBrusentsev can you please confirm? In any case, I am planning to compile this runtime invocation away when Fable 3 comes out so it should be good enough for now

**Comment by VitalyBrusentsev** [comment]
I have updated Feliz to 1.10 and can confirm that the app works with preact!
Good job 👍

**Comment by Zaid-Ajaj** [comment]
@VitalyBrusentsev Thanks a lot for confirming! That's great news :smile: @BennieCopeland and @l3m Can you please check again if Feliz is working like it should with Preact? :pray:

**Comment by Zaid-Ajaj** [comment]
I will assume Preact support is fixed, please re-open if the issue persists :smile:
