### ISSUE TITLE
Redux DevTools: Recording of Events from within Function Components?

### ISSUE THREAD

**Issue by aspnetde** [Zaid-Ajaj/Feliz#207]
I've nicely split up my sample app in two function components, which massively reduces the ceremony of child-parent communication. However, I noticed that the recording of events through the Redux DevTools only work for the top level events (`SignIn` and `SignOut` in the App module).

See the following recording: https://www.dropbox.com/s/w9v8lo0erv1yumw/Screen%20Recording%202020-06-12%20at%2001.47.13.mov?dl=0

Is there a way to work around this, or is this just a tradeoff that comes with using this approach instead of a single application-wide message loop?

Cheers

Thomas

**Comment by MangelMaxime** [comment]
Hello @aspnetde,

If you have the Elmish program with his "main" loop and have sub-components (not using the Main loop) which don't use the main loop then:

Only the message that goes into the "Main" loop is tracked. Indeed, `Elmish.withDebugger` is hooked at the "main" loop level.

If you want to track message in sub-components (not using the Main loop) then you need to write your own code to send the information to the DevTool. So DevTool will have 3 "instances" to track in your case.

------------

When looking at your code you can see that first, you don't have 1 single state but at least 3 states in your application.

- 1 : "Main" program state
- 2 : State stored inside your function components `let state, dispatch = React.useElmish)`

It is kind of like you had 3 differents Elmish program running in parallel and they don't really communicate with each other. Not exactly true because the main program initiates the 2 others but that's it.

We could say that here you are creating a React application using Elmish components and not creating a (single) Elmish application using React components. <-- I am not sure if this explanation is really clear.

In a similar, way I don't think HMR will work out the box in your case because your state is not stored in a single place. So only the "Main" level is being handled by "Program.withHMR" and if you want to support HMR for your function component you need to wire it yourself. Or it needs to be done by `React.useElmish`.

----

Note for the maintainer of  `React.useElmish`

Because `React.useElmish` is kinda standalone Elmish program then if people want to use DevTools or HMR, you either neither to show them how to wire them. Or you do it by default when in `DEBUG` mode.

However, each instance of `React.useElmish` will create it's own instance to track in DevTools. If you have 100 `React.useElmish` components then you have 100 instances in DevTools.

I think for the HMR it is less of a problem because everything is hidden from the user.

**Comment by aspnetde** [comment]
> We could say that here you are creating a React application using Elmish components and not creating a (single) Elmish application using React components. <-- I am not sure if this explanation is really clear.

It is and it has been before to me :-). My question more or less is, if this (making all existing message loops known to the debug tool) is already considered/being worked on/or even solved.

> In a similar, way I don't think HMR will work out the box in your case because your state is not stored in a single place. So only the "Main" level is being handled by "Program.withHMR" and if you want to support HMR for your function component you need to wire it yourself. Or it needs to be done by React.useElmish.

In fact, that works out of the box!

**Comment by Zaid-Ajaj** [comment]
> In fact, that works out of the box!

Yes, it works in the top-level Elmish program but I believe that hooks in sub components reset their state upon an incremental update. This is the only reason why the Feliz template is still full Elmish by default where HMR works correctly. 

This issue is currently tracked in #203 and technically the solution is there but needs some more investigation on why generated Fable code doesn't work React's FastRefresh. 

Note that this problem is not unique to Feliz. The same issue arises in Fable.React as well when it comes to implementing standalone components using hooks.

**Comment by aspnetde** [comment]
> Yes, it works in the top-level Elmish program but I believe that hooks in sub components reset their state upon an incremental update. This is the only reason why the Feliz template is still full Elmish by default where HMR works correctly.

Ah, right. I didn't notice that because I had not any stateful part in my components yet.
