### ISSUE TITLE
memo doesn't work

### ISSUE THREAD

**Issue by OnurGumus** [Zaid-Ajaj/Feliz#209]
I have tried the below code but, it seems it is always being rerendered
```
       React.memo((fun (props:{|i : int|}) ->
        printf "onur";
        Html.div [
            //renderCount {| label = "Button" |}
            Html.button [
                prop.onClick <| fun _ ->  dispatch (TargetRangeFilterChanged(0.,1.))
                prop.text "Show renders"
            ]
        ]), areEqual = (fun _ _ -> true)){| i = 0|}
```

**Comment by Zaid-Ajaj** [comment]
is `React.memo` defined as a module-level value? As per [Common Pitfalls](https://zaid-ajaj.github.io/Feliz/#/Feliz/React/CommonPitfalls)

i.e. What happens when you do this
```fs
let myMemoComponent = React.memo((fun (props:{|i : int|}) ->
        printf "onur";
        Html.div [
            //renderCount {| label = "Button" |}
            Html.button [
                prop.onClick <| fun _ ->  dispatch (TargetRangeFilterChanged(0.,1.))
                prop.text "Show renders"
            ]
        ]), areEqual = (fun _ _ -> true))
```
then somewhere in the app
```
Html.div [ myMemoComponent {| i = 0 |} ]
```

**Comment by Shmew** [comment]
A couple things in addition to what @Zaid-Ajaj said, `areEqual` is not for *overriding* the functionality of memo, but to work as a performance optimization. 

See the [React docs on this](https://reactjs.org/docs/react-api.html#reactmemo):
> This method only exists as a performance optimization. Do not rely on it to “prevent” a render, as this can lead to bugs.

You have a dispatch in the body of that component, I assume this is because you're either nesting the component, at which point @Zaid-Ajaj's comment covers it. If not, you will need to make sure you wrap the function (if it's not returned via `React.useElmish`) with a `React.useCallback` or `React.useCallbackRef`.

**Comment by OnurGumus** [comment]
With Zaid's way it works. I should have read the docs more carefully it seems. Thanks. @Shmew I have passed the dispatch via props.
