### ISSUE TITLE
ReactComponent Type Provider

### ISSUE THREAD

**Issue by jkone27** [Zaid-Ajaj/Feliz#235]
I just start saying Feliz is AWESOME!!!! 

would it be possible (in a human way :D ) to have a **React component library type provider**, in a similar way of the one used for Importing custom CSS?
So that e.g. one could do

```fsharp
type ANTD = ReactComponent<"path/to/antd.css", "path/to/antd.js">

//and then just regular Feliz...
<Html.h1>My Date Picker</Html.h1>
<ANTD.DatePicker onChange={value => this.handleChange(value)} />
```

i see there is a [fable binding project for antd,](https://github.com/uxsoft/Fable.AntD) i guess this is one of the most used UI component libraries for reactjs,
so that would be a very big speedup in development 

what do you think? 

Cheers

**Comment by Zaid-Ajaj** [comment]
Hi @jkone27, I am glad to hear you enjoy working with Feliz :smile: 

About the type provider, unfortunately I don't think it is possible to build one in such a generic way to support many different binding libraries 😞 this is because the type metadata of the components is not always up to date and is sometimes missing and the we as developers building these bindings, would have to fill in these gaps. Each React library or frameworks can be vastly different so when we translate those into F#, we usually have to customize the way they are used to make them F# friendly or more type-safe (which some libraries don't even care about) 

I will be exploring an automated solution in the near future but probably it won't be a type-provider and it would be specific to certain libraries, especially AntDesign.

**Comment by jkone27** [comment]
Thanks @Zaid-Ajaj  that would be awesome, i mean to be able to show pp that a component library like ANT design is ready to be used in F#, that would be very impressive :))))

i don't know Material UI but i will try to experiment a bit with this one in the mean time https://cmeeren.github.io/Feliz.MaterialUI/#usage/components-props

Feliz is Super!!!! 🥇
