### ISSUE TITLE
Make types static classes

### ISSUE THREAD

**Issue by Shmew** [Zaid-Ajaj/Feliz#257]
By applying the `AbstractClass` and `Sealed` attributes to things like `Html`, `props`, `style`, `color`, `React`, etc users can open them using the open static class feature.

so `Html` would look like

```fsharp
[<AbstractClass;Erase;Sealed>]
type Html =
	...
```

Is there any downside/reason as to why we shouldn't implement this?

How does this work when we have both a module and type?

**Comment by MangelMaxime** [comment]
Just adding a special case that can be encounter in some of Feliz libraries.

It is probably what you meant by "How does this work when we have both a module and type?" but just to be sure I prefer to mention it with an example :)

```fs
[<Fable.Core.Erase>]
type Bulma =
    static member inline container props = ElementBuilders.Div.props ElementLiterals.``container`` props
    static member inline container (elms:#seq<ReactElement>) = ElementBuilders.Div.children ElementLiterals.``container`` elms
    static member inline container elm = ElementBuilders.Div.valueElm ElementLiterals.``container`` elm
    static member inline container s = ElementBuilders.Div.valueStr ElementLiterals.``container`` s
    static member inline container i = ElementBuilders.Div.valueInt ElementLiterals.``container`` i

    // ...

module Bulma =

    [<Fable.Core.Erase>]
    type button =
        static member inline button props = ElementBuilders.Button.props ElementLiterals.``button`` props
        static member inline button (elms:#seq<ReactElement>) = ElementBuilders.Button.children ElementLiterals.``button`` elms
        static member inline button elm = ElementBuilders.Button.valueElm ElementLiterals.``button`` elm
        static member inline button s = ElementBuilders.Button.valueStr ElementLiterals.``button`` s
        static member inline button i = ElementBuilders.Button.valueInt ElementLiterals.``button`` i

        static member inline a props = ElementBuilders.A.props ElementLiterals.``button`` props
        static member inline a (elms:#seq<ReactElement>) = ElementBuilders.A.children ElementLiterals.``button`` elms
        static member inline a elm = ElementBuilders.A.valueElm ElementLiterals.``button`` elm
        static member inline a s = ElementBuilders.A.valueStr ElementLiterals.``button`` s
        static member inline a i = ElementBuilders.A.valueInt ElementLiterals.``button`` i
    // ...
```

In Feliz.Bulma we do that in order to provide specialized helpers for components/element that can use different HTML element in the output.

User write: `Bulma.button.button` or `Bulma.button.a` depending on the HTML element he wants as the host of the component. Currently, from the user point of view, there is no difference between `Bulma.container` and `Bulma.button.X`

I do hope that if we make the class static and open it then it will also open the module so people can consume `container [ ... ]` and `button.div [ ... ]` transparently.

TBH I am not a big fan of the not prefixed version because you lose information but I guess it is a matter of personal preference as with everything in the DSLs world.

I don't know if Feliz use this kind of module/class mix or if this is encounter only in sub library like Feliz.Bulma but I think the discussion as it places in Feliz repo as it can shape what people are expecting to see in other Feliz libraries. And if we can keep thing coherent inside the eco-system it would be great :)

If Feliz offers prefix API and non-prefix API the libraries in the ecosystem should probably do the same too.
If non-prefix API can't be supported by other libraries then we need to choose if we want to provide a coherent API everywhere or not.

**Comment by Zaid-Ajaj** [comment]
@Shmew Is this still an issue? latest F# features work fine with the static as they are now, correct?

**Comment by Shmew** [comment]
Yeah I saw a thread on twitter of someone opening them as they are now.
