### ISSUE TITLE
Feliz demo

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Zaid-Ajaj/Feliz#261]
Is there something like Fulma demo written with Feliz? https://github.com/MangelMaxime/fulma-demo

I would like to send a PR to upgrade it to Nagareyama that can be used as reference to others willing to try out Fable 3.

Thanks! @Zaid-Ajaj @MangelMaxime @Shmew

**Comment by MangelMaxime** [comment]
Hello on my side, I think the only public "demo" I have is the Fable REPL so not really best suited for this usage.

**Comment by Zaid-Ajaj** [comment]
Hi @alfonsogarciacaro, I think the best demo out there is actually the application in the `/docs` directory which makes up the docs at [zaid-ajaj.github.io/feliz](zaid-ajaj.github.io/feliz). It has many pages and uses many components 

I also think trying out Fable 3 with the tests in Fable.SimpleJson repo would be great too because these have lots of Fable-specific code with respect to generics, equality and reflection

**Comment by Shmew** [comment]
The [Fable.Jester](https://github.com/Shmew/Fable.Jester) repo has a few hundred unit tests which includes rendering tests via react-testing-library. It's not a target that would be great for showing others how to try it out, but it's likely a very fast way to test out if it works as expected.

**Comment by halcwb** [comment]
For a demo written by a non-professional programmer like me: http://gencalc.nl. Demonstrating how awesome Feliz is. 

I think a list of web apps written using Feliz would be very useful.

**Comment by alfonsogarciacaro** [comment]
This is great @halcwb, thanks a lot! If the source code is available somewhere I can send a PR to upgrade Fable to Nagareyama and see how it works.

**Comment by halcwb** [comment]
@alfonsogarciacaro: These apps are created with Feliz and Feliz.MaterialUI:

- https://github.com/halcwb/PediatricRiskCalculator
- https://github.com/halcwb/PICEDashboard
- https://github.com/halcwb/GenPedForm

The PediatricRiskCalculator is a client app only.
