### ISSUE TITLE
Trying to use prop.min with a DateTime but it only allows int or float

### ISSUE THREAD

**Issue by CallumVass** [Zaid-Ajaj/Feliz#267]
Hi,

I tried using prop.min with a DateTime, however, it wasn't possible as it only allows int or float values.
To get around it I did the following which seemed to work:

`Interop.mkAttr "min" minDate` where `minDate = myDate.ToString("yyyy-MM-dd")`

So a possible solution could be to add an overload to the `min` property like so:

```
static member inline min (value: DateTime) = 
  let dateAsString = value.ToString("yyyy-MM-dd")
  Interop.mkAttr "min" dateAsString
```

If you're happy with that solution, I'm happy to create a PR for it. Thanks

**Comment by Shmew** [comment]
Ah, yeah that's a good idea. You can pass numbers here and since `Date`'s primitive value is a number you can actually just give it that (at least I know you can with `value`).

```fsharp
static member inline min (value: DateTime) = Interop.mkAttr "min" value
```

If it gets picky with that you can call `Date`'s `valueOf()` instance method on on the `DateTime` like this: `value?valueOf()`. 

> I'm happy to create a PR for it.

Yes, a PR is very much welcome!

**Comment by CallumVass** [comment]
Hi,

I've added min as DateTime. Additionally to test it I added a new test page for the inputs function which wasn't being used in the Example file.
