### ISSUE TITLE
What's the purpose of prop.valueAsDate?

### ISSUE THREAD

**Issue by CallumVass** [Zaid-Ajaj/Feliz#268]
Hi,

I tried using prop.valueAsDate like so:
```
Html.input [ prop.type' "date"
                    prop.valueAsDate myDate ]
```
However, this gives off a warning and doesn't work as I expected (the input didn't have the value set):

    React does not recognize the `valueAsDate` prop on a DOM element

To get around it, I did the following
```
let dateAsString = myDate.ToString("yyyy-MM-dd")
Html.input [ prop.type' "date"
                    prop.valueOrDefault dateAsString ]
```

So I just want to know what the purpose of `valueAsDate` is? It doesn't seem to provide anything and leads to confusion?

**Comment by Shmew** [comment]
Looks like this is an [issue with React](https://github.com/facebook/react/issues/11369), we should probably comment this property out until that's resolved.

**Comment by CallumVass** [comment]
Oh wow. That's an old issue. Judging by the comments it looks like `valueAsNumber` won't work either but I haven't tried that

**Comment by CallumVass** [comment]
Closing as this is an issue with react. Not with Feliz.

**Comment by Zaid-Ajaj** [comment]
@Shmew maybe we do the conversion internally in Feliz when the input is a date? I am just not sure whether the format is culture-specific or that it needs a higher precision to include the time of the day, not just the date 🤔

**Comment by Shmew** [comment]
Yeah, I'd personally rather just comment them out, but both sound fine to me.

**Comment by Zaid-Ajaj** [comment]
As of v1.37 the functions `valueAsDate` and `valueAsNumber` are no longer a thing because I couldn't find anything in React that corresponds to them. Instead, I have added `DateTime` utilities in Feliz that makes working with the native date selector a breeze. See [Working with Dates](https://zaid-ajaj.github.io/Feliz/#/Feliz/React/WorkingWithDates) for examples 

![Feliz-Dates](https://user-images.githubusercontent.com/13316248/110385600-6cc48900-805f-11eb-9aaa-d42ca00eb7b8.png)
