### ISSUE TITLE
useEffect hook usage with dependencies proposal

### ISSUE THREAD

**Issue by aitoroses** [Zaid-Ajaj/Feliz#274]
Current hooks API is not ergonomic enough when working with dependencies, it requires to cast always the used values as objects. It would be interesting to use an API more similar to what `reason-react` does [here](https://github.com/reasonml/reason-react/blob/master/src/React.re#L214), by creating specialized functions:

**Current**

```
React.useEffect ((fun () -> (), [| 1 :> obj, "hello" :> obj |])
```

**Proposal**

```
// useEffect: (effect: unit -> unit) -> unit  // no dependencies
// useEffect0: (effect: unit -> unit) -> unit  // implicit empty array as dependencies
// useEffect1: (effect: unit -> unit, deps?: 'a []) -> unit
// useEffect2: (effect: unit -> unit, deps?: 'a * 'b) -> unit
// useEffect3: (effect: unit -> unit, deps?: 'a * 'b * 'c) -> unit
....

React.useEffect2 ((fun () -> ()), (1, "hello"))
```

This applies for other hooks too!

**Comment by Zaid-Ajaj** [comment]
Hi there @aitoroses, 

The reason we are using a dependencies array, is to keep the public API as close as possible to its React equivalent and reduce the number of function overloads because those lead to mangled JS output filled with overload hashes generated by Fable. 

I tend to believe that having just an extra function call to `box` on each array element shouldn't be that much big of a deal but depending on your situation it might be different. Instead of casting, you can call `obj`:
```fs
React.useEffect ((fun () -> ()), [| box 1; box "hello" |])
```

**Comment by Shmew** [comment]
I also want to point out that `box` and `unbox` are erased by Fable during compilation, so there's no runtime issues with this.

It is possible to add these overloads and do it in such a way that it's erased, but it still diverges from the React API. They also would need to be non-optional otherwise it can't resolve the correct overload:

```fsharp
type React with
    static member inline useEffect (effect: unit -> unit, dep1: 'a, dep2: 'b) =
        React.useEffect(effect, [| dep1 :> obj; dep2 :> obj |]
    static member inline useEffect (effect: unit -> unit, dep1: 'a, dep2: 'b, dep3: 'c) =
        React.useEffect(effect, [| dep1 :> obj; dep2 :> obj; dep3 :> obj |]
    ...
``` 

You'd also then need to add overloads for when they return `System.IDisposable`. It all adds up pretty quickly.

**Comment by Zaid-Ajaj** [comment]
For now, I would like to keep the current API as close as possible to React. Will revisit if a lot of people complain about it 😉
