### ISSUE TITLE
Same component name in different modules - Identified has already been declared error

### ISSUE THREAD

**Issue by Dzoukr** [Zaid-Ajaj/Feliz#286]
Hello friend,

I am not sure (again 😄) if this is me doing something stupid or it's bug.

I have two components named "view" and decorated with `[<ReactComponent>]` attribute. Each of them in different module. Having code like this results in error during fable build:

```fsharp
ERROR in ./.fable-build/View.js
Module build failed (from C:/Dzoukr/Personal/dzoukr/SAFEr.Template/src/node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Dzoukr\Personal\dzoukr\SAFEr.Template\src\src\SAFEr.App.Client\.fable-build\View.js: Identifier 'View' has already been declared (12:16)
```

Funny thing is, that when I name them "View" (with upper-case V), it works.

**Comment by Shmew** [comment]
I suspect this is a conflict between plugins and Fable's name collision resolution. 

cc @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
When you say different modules, you mean different files, right? When the function name starts with lower case the plugin converts it to upper case to play better with React tooling. Not sure in what point exactly, but I assume this is conflicting with Fable name collision resolution and it causes two references to have the same name. There are two ways to solve this:

1. Add more compiler and plugin magic to try to fix this case.
2. Instead of trying to capitalize automatically, add a warning recommending users to capitalize by themselves 👈 👈 👈 ❤️ 😍 ❤️ 🕺 🎉  🥇🎉 👍 🎉 🥇 👍 🕺 _(pick me, pick me!)_

Just in case you're wondering, I would prefer the second option 😉

**Comment by Zaid-Ajaj** [comment]
@Dzoukr Nah, this is a bug in the code generation of the plugin :smile:

@alfonsogarciacaro Emitting a warning is probably the way to go, I'll rework the compiler plugins soon before I start working on the documentation & caveats. First, I am trying to figure out why records break React tooling...😓

**Comment by Dzoukr** [comment]
HA! Finally something 😄 

Yup, it's in different file, but no problem, I can name them by myself (and agree with @alfonsogarciacaro that probably well documented rule with compiler warning would be easier for you and cleaner than some kind of black magic).

**Comment by Zaid-Ajaj** [comment]
Hi Roman, latest Feliz v1.22 has been pushed to nuget and it will no longer automatically uppercase the function name. Instead, it will emit a compiler warning that tells kindly asks you to do it yourself which allows Fable to resolve naming collisions on its own :smile:

**Comment by Dzoukr** [comment]
Thanks a lot, mate!
