### ISSUE TITLE
Why doesn't prop.ref match my generated innerRef interop?

### ISSUE THREAD

**Issue by OkayX6** [Zaid-Ajaj/Feliz#338]
Hi :)
I had to do some unfortunate dynamic typecast in this situation.

## I was translating this official JS code from (ReactBeautifulDnd) 

```jsx
<div
  ref={provided.innerRef}
>
```

#### div.ref
![image](https://user-images.githubusercontent.com/1169339/112588651-56297a80-8e32-11eb-9ec4-97c60335e067.png)

#### provided.innerRef

![image](https://user-images.githubusercontent.com/1169339/112589044-01d2ca80-8e33-11eb-9360-72e2b0a573f5.png)

### But the types (that I got from TS2Fable) forced me to do some weird conversion

```fsharp
div [
  prop.ref (fun (elt: Element) -> provided.innerRef (Some (elt :?> HTMLElement)) |> ignore)
]
```

#### Feliz prop.ref

![image](https://user-images.githubusercontent.com/1169339/112589198-4a8a8380-8e33-11eb-9e93-7b6e6d73a073.png)

#### Generated F# provided.innerRef

![image](https://user-images.githubusercontent.com/1169339/112589226-55ddaf00-8e33-11eb-8ec7-9d5e86baedea.png)

## Diagnostic

I didn't take the time yet to look thoroughly in the Feliz codebase, but

`HTMLElement` is a subtype of `Element`, that's why it doesn't work here.
In the original JS/TS code, `HTMLDivElement` is passed as an `HTMLElement`, which works here.

Is it by design in Feliz ?

**Comment by Zaid-Ajaj** [comment]
Hi there @OkayX6, this is an interesting situation. I think the generated type by ts2fable is wrong and it should be
```fs
val innerRef : HTMLElement -> unit
```
instead of
```fs
val innerRef : HTMLElement option -> obj
```

On the Feliz side of things, I might need to add another overload for `HTMLElement -> unit` or change the current one to `#Element -> unit` I am not sure but I will check.

**Comment by OkayX6** [comment]
Oh, I didn't dare touching it, as the original TS code had this signature:

```typescript
export interface DroppableProvided {
    innerRef(element: HTMLElement | null): any;
}
```

**Comment by Zaid-Ajaj** [comment]
@OkayX6 Yeah the problem is in the ts declaration too because in ts I don't think there is a `unit` or `void` type either 😓 this is why I don't use ts2fable anymore. I will see what I can do

**Comment by Zaid-Ajaj** [comment]
@OkayX6 Actually I don't think I can do anything here because there will not be an overload that expects `something -> obj`. The return type of the ref must be `unit` and it is really a problem in ts2fable. 

To simplify your own code, you can `unbox` the value 
```fs
div [
  prop.ref (unbox provided.innerRef)
]
```
I _think_ it should work but I'll the leave the issue at that
