### ISSUE TITLE
Question: ReactComponent annotation with currying 

### ISSUE THREAD

**Issue by njlr** [Zaid-Ajaj/Feliz#346]
From the docs, I know that this:

```fsharp
[<ReactComponent>]
let App (x : string) =
  Html.h1 x
```

Is equivalent to `React.Component<string, obj>`

But what about this?

```fsharp
[<ReactComponent>]
let App (x : string) (y : string) =
  Html.h1 ("x: " + x + " y: " + y)
```

 * `string -> React.Component<string, obj>` ?
 * `React.Component<string * struing, obj>` ?

Is this even a valid usage of the annotation?

**Comment by Zaid-Ajaj** [comment]
When in doubt, always look at the generated code :wink: 

This component is indeed valid
```fs
[<ReactComponent>]
let App (x : string) (y : string) =
  Html.h1 ("x: " + x + " y: " + y)
```
and it translates to:
```js
export function App(appInputProps) {
    const y = appInputProps.y;
    const x = appInputProps.x;
    const value = (("x: " + x) + " y: ") + y;
    return createElement("h1", {
        children: [value],
    });
}
```
In component terms, the input props is an _object_ that contains `x` and `y` values:
```fs
React.Component<{| x: string; y: string |}, obj>
```
On call-site, when you apply the function fully
```fs
App "Hello" "World"
```
the generated JS applies each property
```js
import { createElement } from "react" 
createElement(App, {
    x: "Hello",
    y: "World",
});
```
When partially applied, 
```fs
App "Hello"
```
a function is created
```js
(y) => createElement(App, { x: "Hello", y: y, });
```
Though I would recommend building components using _explicit parameters_ when partially applying another component
```fs
[<ReactComponent>]
let UsingApp (y: string) = App "Hello" y

UsingApp "World"
```
Instead of 
```fs
// DON'T DO THIS
[<ReactComponent>]
let UsingApp = App "Hello" 
```

**Comment by njlr** [comment]
Thanks for this, turns out the library is even smarter than I expected!
