### ISSUE TITLE
React.useState and React.useRef compatibility

### ISSUE THREAD

**Issue by JaggerJo** [Zaid-Ajaj/Feliz#353]
`Feliz.React.useState` returns a tuple. While this is handy to desonstruct it into a `currentValue` and a `setValue`  function it is incompatible with what `useRef` returns.

it would be nice if both would return a similar enough result so that changing a `useRef` to a `useState` does not require changing the whole component.

current solution is to directly use the react took `Fable.React.HookBindings.Hooks.useState`

**Comment by Zaid-Ajaj** [comment]
> Feliz.React.useState returns a tuple. While this is handy to desonstruct it into a currentValue and a setValue function it is incompatible with what useRef returns.

`React.useState` returns a tuple because that is exactly what the JS equivalent looks like and it is a goal of Feliz to be as much as close to what the React corresponding code looks like. 
```js
import { useState } from 'react'
const [const, setCount] = useState(0)
```
It can be the case that `React.useRef` is the exception to the rule here but that is OK because `useRef` and `useState` are _not_ interchangeable: the former uses a mutable value and the latter an updater function. 

That said, you can easily wrap `useRef` in another hook that returns you a tuple if that is what you want

**Comment by JaggerJo** [comment]
@Zaid-Ajaj wow, that was quick 😁

What I want is actually the other way around (have it return a `IRefValue` / `IStateHook`).

I totally get you point tho, and yes it's not a 100% interchangeable 🙃

I'll just close this and use a custom extension
