### ISSUE TITLE
Feliz depends on a broken version of Fable.React

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Feliz#355]
See https://github.com/fable-compiler/Fable/issues/2414#issuecomment-826115001

I am almost certain that Fable.React 7.0.1 is a broken package and Feliz is having a minimal dependency on it.

I am proposing to upgrade the dependency constraint to at least Fable.React 7.0.3 which has a fix for it.

**Comment by Zaid-Ajaj** [comment]
Hi @MangelMaxime thanks for the report. Yes in seems that Feliz needs to update Fable.React, though most Feliz users don't consume anything from Fable.React so I guess that is why no errors have been surfaced yet. 

I will update Fable.React, however, it seems that latest Fable.React v7.3 relies on FSharp.Core >= 5.0 meanwhile Feliz takes FSharp.Core >= 4.7.2 which I would like keep (so that no breaking changes happen to users with previous sdk) would it be possible to lower FSharp.Core to v4.7.2 on the Fable.React repo and publish a version from there? That would be great!

**Comment by MangelMaxime** [comment]
Personally, I don't see any problem to lower the FSharp.Core version just pinging @alfonsogarciacaro @forki here as they probably know a bit better than me the implication of it.

**Comment by Zaid-Ajaj** [comment]
Lowering FSharp.Core to 4.7.2 means that the repository Fable.React won't be able to use latest features of F# such as string interpolation but it makes more compatible where users are still one netcore 3.1 for example

**Comment by MangelMaxime** [comment]
That's what I thought, I just don't know if @alfonsogarciacaro had a "reason" to upgrade this dependency.

**Comment by Zaid-Ajaj** [comment]
If you don't explicitly say what FSharp.Core should be, it will infer the version from the SDK, so @alfonsogarciacaro probably had updated the .NET sdk to 5.x and published a new version of Fable.React that inferred FSharp.Core to be v5

**Comment by MangelMaxime** [comment]
@Zaid-Ajaj I just released Fable.React 7.4.0 which lower the requirement for FSharp.Core to 4.7.2

**Comment by Zaid-Ajaj** [comment]
Thanks @MangelMaxime I just published Feliz v1.44 which depends on Fable.React v7.4 🚀
