### ISSUE TITLE
Question: how to correctly pass children to JSX component

### ISSUE THREAD

**Issue by bzuu** [Zaid-Ajaj/Feliz#359]
While trying out the ability to import JSX components in Feliz I ran into an issue when creating components that have children. When I do this I see the warning `Each child in a list should have a unique "key" prop.`. I suppose this may be related to #21, but am not sure how one can spread the children in this case?

Here is a minimal example to demonstrate the issue:

```jsx
import React from "react"

export const MyList = ({ children }) => {
    return <ul>{children}</ul>
}
```

```fsharp
module Sample

open Feliz
open Fable.React

type Components =
    [<ReactComponent(import = "MyList", from = "./Components.jsx")>]
    static member MyList(children: ReactElement seq) = React.imported ()

[<ReactComponent>]
let Sample () =
    Components.MyList [ Html.li "hi"
                        Html.li "there"]
```

**Comment by Zaid-Ajaj** [comment]
The warning you are getting is actually the "most correct React code" because you are supplying a list of which the size can be dynamic so React asks you to give it keys. Unfortunately, in Feliz there is no easy way to determine a dynamic list from a static one and spread the elements across the `createElement` call from React. `prop.children` only suppresses the warning by giving the elements artificial keys using React's `Children.toArray` function. 

In this case, the plugin could potentially detect that you have a parameter called `children` and wrap it with `Children.toArray` as a fix to the problem but as of now there no workaround for this :/

**Comment by MangelMaxime** [comment]
Hello, 

as @Zaid-Ajaj said what you are seeing is the expected behaviour based on how Feliz use React: using `prop.children` instead of spreading the element across `createElement`.

To complete @Zaid-Ajaj answer, you can also decide to set the `prop.key` by yourself on the `li` elements.

It can feels overkill for a simple component like in your example but if it was a more complex components it would makes sense because this help React decide when to re-use an existing DOM element instead of dumping everything and re-creating it which is really costly. 

There was a similar discussion in the past in this issue https://github.com/Zaid-Ajaj/Feliz/issues/21

There is also a great talk which happened at FableConf 2018: https://www.youtube.com/watch?v=9VJoaNoutm4
The talk is using Fable.React because Feliz was not around but the same principle hold on because it is about how React works and why we should do stuff like setting key property when passing a list of children.

If you don't want to use meaningful keys you can always use `Interop.reactApi.Children.toArray` which will populate the key properties using an increment value.

For example, it is how Feliz is doing it under the hood:
https://github.com/Zaid-Ajaj/Feliz/blob/be1bea11a65df557b7e161048cd06f3c6a2aeed2/Feliz/Properties.fs#L434

**Comment by bzuu** [comment]
Thanks @Zaid-Ajaj and @MangelMaxime for both your very helpful answers. It does make a lot more sense now.

I also see why the behaviour in other places kind of 'hides' the issue as the title of #21 suggests. I'll definitely go and watch the video when I have some time as it may give me some more background into how things work under the hood. For now I think the main takeaway is to try and provide meaningful keys whenever I can :)

**Comment by Zaid-Ajaj** [comment]
@bzuu  A simple solution to this could be that instead of `ReactElement list`, you take one `ReactElement` and use a `Html.div` or `React.fragment` as the root element

**Comment by bzuu** [comment]
@Zaid-Ajaj that is indeed a workaround I considered. Mostly though I wanted to know if I missed something when using JSX components. And it seems providing meaningful keys is the thing I missed :) Thanks!
