### ISSUE TITLE
Creating nested react components

### ISSUE THREAD

**Issue by LuisFX** [Zaid-Ajaj/Feliz#419]
Hi, I'm trying to start writing bindings for the ionic framework. I'm having issues (probably of lack of understanding):

```
//Ionic wrappers
type Ion =
    [<ReactComponent(import="IonApp", from="@ionic/react")>]
    static member App obj = React.imported()
    [<ReactComponent(import="IonContent", from="@ionic/react")>]
    static member Content obj = React.imported()

let viewIonic (state: AppState) (dispatch: AppMsg -> unit) =
    Ion.App[
        Ion.Content [
            Html.h1 "HELLO ION IN FELIZ"
        ]
    ]
```

The code above outputs the following html:

```
<ion-app></ion-app>
```

But I was expecting to see this:

```
<ion-app>
  <ion-content>
    <h1>HELLO ION IN FELIZ</h1>
  </ion-content>
</ion-app>
```

Can someone please tell me what I'm doing wrong? Or maybe share a link where I can learn how to write this properly?

Thank you much!

**Comment by LuisFX** [comment]
I'm actually trying to really wrap my head around what the best approach would be. The approach I'm trying to go for above, is "wrapping" the library's react components... but in reality, it seems like all those react components do, is write "custom" tags with classes. So, it seems to me that the best approach would be to just output the html myself like so:

```
[<AutoOpen>]
module Feliz.Extension

open Feliz

type Ion with
    static member inline app xs = Interop.createElement "ion-app" xs
    static member inline app (children: #seq<ReactElement>) = Interop.reactElementWithChildren "ion-app" children
.
.
.
```

Basically, just as feliz.bulma is written. Please advise.

Thanks again.

**Comment by MangelMaxime** [comment]
Using `Interop.createElement "ion-app" xs` probably works if you are including Ionic WebComponents version.

If you want to write a binding for a React library my go to is to look at the `Feliz.Recharts` library. The structure goes like that

**Types.fs**

Define types and also interface used to represents the elements properties. This make the bindings more strict and type safe, for example like that you can't apply a `IContentProperty` to a `App` element.

```fs
// Types.fs
namespace Feliz.Ion

[<Erase>]
type IAppProperty =
    interface end

[<Erase>]
type IContentProperty =
    interface end
```

**Interop.fs**

In this module, we put some interop helpers. This is useful, because we are hiding `unbox` being a type.

```fs
namespace Feliz.Ion

module Interop =

    let inline mkAppAttr (key: string) (value: obj) : IAppProperty = unbox (key, value)
    let inline mkContentAttr (key: string) (value: obj) : IContentProperty = unbox (key, value)
```

**Ion.fs**

This is the main file where you will declare your exposed bindings API. If the file goes to big, you can always move type into their own files because we are using `namespace`.

```fs
namespace Feliz.Ion

open Fable.Core
open Fable.Core.JsInterop

[<Erase>]
type Ion =

    static member inline App (props: #IAppProperty list) =
        Interop.reactApi.createElement(import "App" "@ionic/react", createObj !!props)

    static member inline Content (props: #IAppProperty list) =
        Interop.reactApi.createElement(import "Content" "@ionic/react", createObj !!props)
```

Also, the `[<Erase>]` and `inline` are important because they helps avoid increasing the bundle size with unneeded code constructor, reflection API, etc.

**Comment by LuisFX** [comment]
Damn, you're a savage! That's EXACTLY what I was looking for... I tested a small proof-of-concept, and it works like a charm. Thanks you so much @MangelMaxime !
