### ISSUE TITLE
Router setup in template confusing

### ISSUE THREAD

**Issue by nirvdrum** [Zaid-Ajaj/Feliz#432]
I'm fairly new to F#, Fable, and Feliz, so I apologize in advance if I'm running into things that are well known in the community. Having worked with React in TypeScript and ReasonML, I expected the router to work with various paths. I.e., generating a new application with _Feliz.Template_ 3.16.0 and updating _Main.fs_ to render the router component, I would have expected the following URLs to render:

* http://localhost:8080/
* http://localhost:8080/hello
* http://localhost:8080/counter
* http://localhost:8080/non-existent-path

Instead, on any path other than "/", I see `Cannot GET /hello`. That error message is coming from the Webpack dev server because the generated configuration can only handle requests to `/`. This was fairly confusing because I was definitely seeing an error message, but not the one provided as a fallback case in the `Router` component. I was able to fix that by adding `historyApiFallback: true` to the `devServer` configuration in _webpack.config.js_.

Even with that change, however, the router still doesn't work the way I would have thought. Now all of those paths are handled, but they always render the `"Index"` case. Looking into it, `Router.currentUrl` returns an empty list in all of the URLs I provided above. The sample seemingly expects everything to be handled as a URL fragment. So, the following URLs will work:

* http://localhost:8080/
* http://localhost:8080/#hello
* http://localhost:8080/#counter
* http://localhost:8080/#non-existent-path

Just playing around with it a bit, it looks like `Router.currentPath()` provides information about the actual path and using that instead of `Router.currentUrl()` allows the initial set of URLs to work.

If the Fable/Feliz convention is to use URL fragments for everything, I'm sorry for the noise. Perhaps adding a note to the docs would be helpful. Otherwise, I think the template might not be setting up the router correctly.

**Comment by MangelMaxime** [comment]
You can find information about using path-based URLs instead hash-based URLs in the [Feliz.Router documentation](https://github.com/Zaid-Ajaj/Feliz.Router#using-path-routes-without-hash-sign).

In general, we use hash-based path in example/templates because they are easier to work for a minimal setup. When you use path-based URLs, your browser with make a call to your Web Server to retrieve the page at that location. However, in a SPA (Single Page Application) you often have only a single file to served meaning that if you would do that. You would have to redirect all the request for a page to that file.

For me using path-based URLs makes sense when you are doing SSR (Server Side Rendering) because then you can generate the Page HTML on the fly on the server to make the page load faster.

If you are new to Feliz/Elmish, I would encourage you to just use hash-based URLs for now. You can move to path-based URLs later if needed fairly easily from Feliz/Elmish point of view.

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime pretty much explained it. If there are any questions, please let me know!
