### ISSUE TITLE
Record type allowed in ReactComponent

### ISSUE THREAD

**Issue by forki** [Zaid-Ajaj/Feliz#463]
https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/258

It looks like the issue is closed and I wonder if the warning is now obsolete

![image](https://user-images.githubusercontent.com/57396/157615469-605e30c0-b1c8-4c46-bf71-c75d04a4a3af.png)

**Comment by MangelMaxime** [comment]
Hello @forki,

For me the warning is still valid this days.

For react-refresh, to works it looks at the exposed values from your JavaScript files. React-refresh, is activated only if all the exported values from your JavaScript module are considered ReactComponent. For the detection, they basically looks if everything that is exported is a Function starting in Capital case (I think there are other things accepted but I don't remember exactly).

The problem when you do:

```fs
type TestProps =
    {
        Value : string
    }

[<ReactComponent>]
let Test (props : TestProps) =
    Html.div [
        prop.text props.Value
    ]
```

then you get something like that

```js
export class TestProps extends Record {
    constructor(Value) {
        super();
        this.Value = Value;
    }
}

export function TestProps$reflection() {
    return record_type("Components.Counter.TestProps", [], TestProps, () => [["Value", string_type]]);
}

export function Test(props) {
    return createElement("div", {
        children: props.Value,
    });
}
```

Note how `TestProps` is exported. This prevent react-refresh to be activated.

If you move `TestProps` to another file like for example `Props.fs` and do

```fs
[<ReactComponent>]
let Test (props : Props.TestProps) =
    Html.div [
        prop.text props.Value
    ]
```

then the warning goes away because the `TestProps` is now exported outside of the module.

The proposed solution in warning are a way to encourage you as a user, to write react-refresh compatible code.

## Using function arguments

In these case, Feliz plugin is rewritting the JS code to host the function arguments in a record.

```fs
[<ReactComponent>]
let Test (value : string) =
    Html.div [
        prop.text props.Value
    ]
```

generates

```js
export function Test(testInputProps) {
    const value = testInputProps.value; // <--- See value is now accessed from a record
    return createElement("div", {
        children: value,
    });
}
```

## Anonymous record

By using, Anonymous record Fable will not generate a type for the props and so nothing will be exported

```fs
type TestProps =
    {|
        Value : string
    |}

[<ReactComponent>]
let Test (props : TestProps) =
    Html.div [
        prop.text props.Value
    ]
```

generates

```js
// See how nothing other than the component is exported

export function Test(props) {
    return createElement("div", {
        children: props.Value,
    });
}
```

**Comment by panmau** [comment]
I wonder whether this warning needs to be activated for all users, even those that are not using tools like react-refresh. (I don't really know if that is common)  For users like this, this is a lot of noise that isn't applicable/useful.

**Comment by MangelMaxime** [comment]
React-refresh is now the defacto tool used when using React with any bundler so I think it makes sense to inform the users.

It also encourage people to write "standard" code that is know to works with React and so can avoid potentiel issues.

**Comment by Zaid-Ajaj** [comment]
Hi @forki, it is as @MangelMaxime said, these warnings are still valid and the solution is to either use normal function parameters or put the record definitions in a separate file (seperate JS module)
