### ISSUE TITLE
Is it possible to make this project target to Bolero?

### ISSUE THREAD

**Issue by albertwoo** [Zaid-Ajaj/Feliz#47]
Is it possible to make this project target to Bolero?

**Comment by Zaid-Ajaj** [comment]
It might be possible, I haven't seen any libraries that could share code with Bolero but there no plans to implement anything like this and we are sticking to Fable as the only target for now as we use many Fable-specific functions internally. I think it would be a lot easier to make a Bolero library *inspired* by this API rather than making the implementation details work for both.
