### ISSUE TITLE
Failed to retrieve information about react required by Feliz

### ISSUE THREAD

**Issue by napretep** [Zaid-Ajaj/Feliz#504]
Failed to retrieve information about react required by Feliz

how to solve this problem ?

![image](https://user-images.githubusercontent.com/7680792/185742537-e8a6e233-b4c9-4fe7-ae49-34dacd1cc159.png)

![image](https://user-images.githubusercontent.com/7680792/185742825-0a4a8d88-6bc6-4bbe-ac37-88cbcb4a0f80.png)

![image](https://user-images.githubusercontent.com/7680792/185742857-b0d39a37-7b76-48fa-8b6f-9a65bb24d05e.png)

**Comment by Zaid-Ajaj** [comment]
Hi @napretep thanks for filing the issue! This is probably an error in Femto where it tried to invoke `yarn` but got unexpected results (shape of JSON) I will have a look

**Comment by Zaid-Ajaj** [comment]
Hi there @napretep, I've just to reproduce the issue at hand and wasn't able to. Femto works just fine with the following versions
```
Femto v0.13.0
Yarn v1.22.19
```
If you don't have latest Femto, try updating it using `dotnet tool update Femto` add `-g` if you have installed the tool globally, same for yarn.

**Comment by MangelMaxime** [comment]
@Zaid-Ajaj This issue remind me of https://github.com/Zaid-Ajaj/Femto/issues/92

But I never looked into it and don't know which version of Yarn was used.

**Comment by napretep** [comment]
Both `yarn` and `femto` have been updated to the latest version, still having problems.

Please check this file directly, thank you.

Btw, using `npm` is ok with `femto`

[test_crx.zip](https://github.com/Zaid-Ajaj/Feliz/files/9399804/test_crx.zip)

**Comment by MangelMaxime** [comment]
@napretep 

The zip that you are providing is more or less empty. I don't know what we can do with it.

It would be better to have a reproduction repository with the actual project set up in it. You can push to it Github for example.

And also the version of the version of yarn and femto you are using by running `yarn --version` and `dotnet femto --version` ? Because `latest` is not something precise enough for reproducing the problem.

**Comment by napretep** [comment]
[test_crx.zip](https://github.com/Zaid-Ajaj/Feliz/files/9401332/test_crx.zip)
oh , Sorry for uploading wrong zip , the new one contains is the full code.

**Comment by MangelMaxime** [comment]
@napretep 

Because you don't have a license field in your `package.json` yarn generates a strange response when running `yarn yarn info react versions --json`.

It returns:

```json
{"type":"warning","data":"package.json: No license field"}
{"type":"inspect","data":["0.0.0-375616788","0.0.0-00d4f95c2","0.0.0-0203b6567","0.0.0-0935a1db3","0.0.0-0c756fb-697f004","0.0.0-0c756fb-f7f79fd","0.0.0-0cf9fc10b","0.0.0-0e4135e8c","0.0.0-0eea57724","0.0.0-1022ee0ec","0.0.0-10cc40018","0.0.0-11565a207","0.0.0-11b07597e","0.0.0-1214b302e","0.0.0-12adaffef","0.0.0-132b72d7b","0.0.0-172e...}
```

So you need to add a license field to your `package.json`.

If your project is private you can set it to `"license": "UNLICENSED"` [NPM docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license).

They also recommend setting `"private": true` as an extra security.

**Comment by napretep** [comment]
thank you for your help.
I'd like to advice that if Femto could provide more  error info from the place the process break down, it would be more efficient.
