### ISSUE TITLE
[Feliz.Template] Broken with .NET 7 and nodejs 18.12.1

### ISSUE THREAD

**Issue by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [Zaid-Ajaj/Feliz#538]
I wanted to try out Feliz, but the first time experience is really terrible at the moment.
Just following the documentation I am immediately hit with a build error that Fable could not be found.
This is apparently resolved by adding a `global.json` file as outlined [here](https://github.com/fable-compiler/Fable/issues/3294#issuecomment-1356810237).

Having overcome that hurdle I was hit with another cryptic error:
```
Error: error:0308010C:digital envelope routines::unsupported
```
Which, I think, is caused by a mismatch between latest nodejs LTS version and the outdated webpack version referenced in the templates `package.json`. I found a workaround by adding an environment variable before running `npm start`.
```
$env:NODE_OPTIONS = "--openssl-legacy-provider"
```

**Comment by Zaid-Ajaj** [comment]
Hi @e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd unfortunately the template hasn't been updated in a while to reflect changes in net7.0, node and fable

First of all, since the template is built for Fable v3 in mind, it shouldn't work with net7.0 (only net6.0) so you might need a `global.json` setting the dotnet sdk version to v6 (6.0.400 to be specific) 

About nodejs 18: updating webpack to latest should do the trick or using any other bundler

**Comment by Zaid-Ajaj** [comment]
Testing the latest template version 3.17.0 works like a charm with `node --version` v18.11.0 and `dotnet --version` 6.0.400

I didn't have to add any options

**Comment by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [comment]
I will give it a try, thanks.

**Comment by Zaid-Ajaj** [comment]
Latest Feliz template should have these problems resolved
