### ISSUE TITLE
Prevent confusion between React components and normal functions

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Zaid-Ajaj/Feliz#88]
When designing the API for React function components we wanted to make them easy to use, that's why `FunctionComponent.Of` returns a function that it's immediately callable. However, I'm regretting that decision now because it makes it difficult for users to distinguish between "normal" functions and actual React components (in React apps this is easy because every JSX element is a component, but in F# we don't have the distinction between JSX and rest of code).

I promise the Fable.React API would be more stable now so I don't want to change it there, but since Feliz is still beta maybe there's an opportunity to change it here. If this is done, users wouldn't call function components directly, but instantiate it trough a helper. I've noticed the optional arguments don't match with the rest of the API, so maybe the "builder" style could be used. Something like:

```fsharp
let MyComponent: ReactElementType<MyProps> =
    ReactElementType.empty
    |> ReactElementType.withDisplayName "MyComponent"
    |> ReactElementType.withMemo (fun p1 p2 -> p1 = p2)
    // When the function body is big it's better to put the other config options on top,
    // that's why I'm moving it to the botton
    |> ReactElementType.fromFunction (fun props ->
        ...
    )

let view model dispatch =
    Html.div [
        prop.children [ React.create MyComponent { MyProps... } ]
    ]
```

> I'm not sure how to do it yet, but this may also be a way to avoid the problem `FunctionComponent.Of` has with render functions accepting a props object with generic arguments.

**Comment by SCullman** [comment]
>  I'm regretting that decision now because it makes it difficult for users to distinguish between "normal" functions and actual React components

@alfonsogarciacaro , maybe a stupid question, but why is it important that users make that  distinction?

**Comment by Zaid-Ajaj** [comment]
> I'm regretting that decision now because it makes it difficult for users to distinguish between "normal" functions and actual React components

I have the same question as @SCullman, in fact I am very much in favor of having these function components be *transparently usable* as functions from the caller's point of view, just like with JSX. Here is how I would like to explain React components to others, it goes as follows:

"React function components are functions that return `ReactElement` except that they can have internal state using hooks, you define them using a function and you get the *constructor* back which is itself a function so you could call right away in your `render` functions."

```fs
// normal function
let greet (input: {| name: string |}) = Html.h1 input.name

// React component
let great = React.functionComponent(fun (input: {| name: string |}) -> Html.h1 input.name)

Html.fragment [
  greet {| name = "John" |}
  greet {| name = "Jane" |}
]
```
From the caller point of view, they are the same because [my assumption is that callers] don't care whether they are using a normal function or a React component. This also makes it super simple to translate examples from React docs or tutorials into Feliz DSL. 

Having the builder syntax would only complicate things and it seems it is only there to make users *really* know that they are working with components and not normal functions. 

> When designing the API for React function components we wanted to make them easy to use

I think `FunctionComponent.Of` is also easy to use but I think the problem why people don't use it a lot is because they are not well documented.

**Comment by alfonsogarciacaro** [comment]
Well, I didn't conduct any serious research but I have the impression users of Fable/React/Elmish (myself included) just use plain functions for everything, even when writing reusable components. And only users who know about hooks use function components when they need to add state, reference an HTML element, trigger an effect, etc. But one day, you realize your app is lagging sometimes and try to locate the problems, learn that React has a nice profiler but when you try to use is not helpful at all because the whole app is just one component (the Elmish root view) and in order to profile you now need to change the whole app to start using components.

It'd be nice if Fable users would be more used to write actual React components. I wonder if they don't do it because they look so similar in the code that it feels there's no real distinction.

**Comment by Zaid-Ajaj** [comment]
> It'd be nice if Fable users would be more used to write actual React components. I wonder if they don't do it because they look so similar in the code that it feels there's no real distinction.

This is a screaming to me "DOCUMENTATION!" if users don't know the difference, they will use what they are most familiar with: plain old functions. I don't think that a syntactic difference will remedy the situation but instead well documented examples that explain where React function components makes sense and how can they help diagnose the application performance in combination with Elmish state management

**Comment by Zaid-Ajaj** [comment]
I believe I can close this issue since I wrote about at lenth in [Feliz / React / Not Just Functions](https://zaid-ajaj.github.io/Feliz/#/Feliz/React/NotJustFunctions) 

Please re-open if further discussion is necessary
