### ISSUE TITLE
Move template's app project to separate subdir

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#96]
I propose to add the `App` project in the sample into a separate `App` subdir, as opposed to just have the project files directly in `src`. It would make it simpler to add more app projects if one wishes to split the functionality aross several projects. Also it's more idiomatic .NET.

**Comment by Zaid-Ajaj** [comment]
Although this is subjective on my side, I have deliberately chosen to *keep it simple* with a single project structure because IMO multiple projects unnecessarily complicate your solution where a single project is more than enough in most common use-cases. Also you don't have to consolidate nuget package versions across solution projects. I know paket would solve this too but again, using nuget to lower the entry barrier.

**Comment by cmeeren** [comment]
Fair point.
