### ISSUE TITLE
Consider reversing args in useCallback/useMemo

### ISSUE THREAD

**Issue by zanaptak** [Zaid-Ajaj/Feliz#99]
`useCallback` and `useMemo` currently mimic the exact React function signatures by taking function first, dependency array last.

But the function can be a long inline multiline function just like with function components, so as discussed elsewhere it can be awkward to put the additional arg last after a long function body.

I am wondering if we should reverse the args to be consistent with function components. Or provide overloads allowing both argument orders, so that the React original definition works too (if that's not too confusing).

**Comment by Zaid-Ajaj** [comment]
> But the function can be a long inline multiline function just like with function components, so as discussed elsewhere it can be awkward to put the additional arg last after a long function body.

True, but we had that liberty in defining the `props' -> ReactElement` argument as last one because it would look closer to the React equivalent when defining a function component. With `useCallback` and `useMemo` however, they are direct 1-to-1 bindings of the their react equivalent and I would like to keep that way to make a lot of Reacts docs/knowledge applicable with Feliz
